### ISSUE TITLE
用户数量统计

### ISSUE THREAD

**Issue by Gsllchb** [Gsllchb/Handright#11]
我想统计一下PyLf的**实际**用户数。

倘若您曾经**使用**过此Python库，请给这个帖子:+1:。

~~由于:+1:是**匿名**的，因此你们也无需有任何顾虑。~~
突然发现发送表情并不是匿名的，对不起大家。。。

**Comment by boltomli** [comment]
包了个壳扔在了 <https://beta.rstudioconnect.com/content/9371/>

理论上说参数也都可以暴露出来，但显示效果不太容易控制就没做……

**Comment by Gsllchb** [comment]
@boltomli 赞👍
