### ISSUE TITLE
您好，请问api文档在哪看？有没有关于扰动算法的详细描述？

### ISSUE THREAD

**Issue by ironshangki** [Gsllchb/Handright#12]
请简明扼要地陈述您的问题。

**Comment by Gsllchb** [comment]
API可以用pydoc看。
算法的详细实现还是看源代码吧，目前没有更详细的文档了。

ironshangki <notifications@github.com> 于 2019年8月21日周三 11:13写道：

**Comment by Jyouhou** [comment]
如果我没有错，应该是对每一块“笔划”进行了随机旋转。这个算法会搜索以连通域形式连在一起的像素群，也就是一个单独的笔划或者有重叠部分的一群，然后再随机旋转。

**Comment by Gsllchb** [comment]
完全正确

Shangbang Long <notifications@github.com> 于 2019年8月26日周一 20:34写道：

**Comment by Gsllchb** [comment]
是中文或类似的象形文字吗？

**Comment by ironshangki** [comment]
你说的应该是把STN融入到task network中的那篇吧
