### ISSUE TITLE
标点符号之后的间距太大看起来有点违和，希望可以判断是符号后把word_spaceing减少

### ISSUE THREAD

**Issue by SexyJoJo** [Gsllchb/Handright#15]
希望可以判断是符号后把word_spaceing减少，不是符号则还原

**Comment by SexyJoJo** [comment]
还有个问题是怎么添加背景图片。。

**Comment by Gsllchb** [comment]
你说的这些功能都有，你可以仔细看一下接口文档和pillow的用法。

发送自ProtonMail手机版

--------原始邮件--------
在 2020年3月11日 11:21, SexyJoJo 来信：

**Comment by Gsllchb** [comment]
第一个功能之前版本有，现在被去掉了，我记错了，不好意思。
其实这本质上是字体本身的问题，你可以
* 选用标点留空少的字体；或者
* 将中文标点替换成英文标点。
