### ISSUE TITLE
如果生成文字多于一张图片的话第二张图片似乎没有应用top_margin

### ISSUE THREAD

**Issue by zxkmm** [Gsllchb/Handright#18]
1. 做了什么？
A:一段文字生成了多余一页图片
2. 希望发生什么？
A：第二页的顶部留空空间和第一张一样大
3. 实际上发生了什么？
A：第二页图片似乎没有留出top_margin参数应该预留的空间，导致我的第二张纸在背景图片中预留的题头空间多了一行字
4. 提供必要的环境信息（包括但不限于：PyLf版本、Pillow版本、Python解释器及其版本、操作系统及其版本）
Pillow                 6.2.1
handright          5.5.0
Python               3.8
Win10    MacOS    均复现

**Comment by zxkmm** [comment]
感谢作者！

**Comment by zxkmm** [comment]
[handright.zip](https://github.com/Gsllchb/Handright/files/4808922/handright.zip)

**Comment by Gsllchb** [comment]
请问你发的这个zip包里有能复现这个问题的脚本、图片和文本吗？我需要定位下

**Comment by zxkmm** [comment]
> 
> 
> 请问你发的这个zip包里有能复现这个问题的脚本、图片和文本吗？我需要定位下

抱歉，我只附了图片，整个项目我现在重新附送，再次感谢，入口在form.py
[HandWrite.zip](https://github.com/Gsllchb/Handright/files/4808951/HandWrite.zip)

**Comment by Gsllchb** [comment]
多谢

**Comment by Gsllchb** [comment]
基本可以断定：
你设置的top_margin有问题。
第二页的上边距之所以这么小，因为你设置的就是这么小。
第一页之所以上边距更大，是因为你的文本最开始有个换行符，往下了一行。

**Comment by zxkmm** [comment]
> 
> 
> 基本可以断定：
> 你设置的top_margin有问题。
> 第二页的上边距之所以这么小，因为你设置的就是这么小。
> 第一页之所以上边距更大，是因为你的文本最开始有个换行符，往下了一行。

感谢！抱歉这个问题我疏忽了没有排查，对不起。
