### ISSUE TITLE
关于写字机的扩展特性 Feature required

### ISSUE THREAD

**Issue by RuofengX** [Gsllchb/Handright#19]
Considering this project is aiming to simulate Chinese Characters， so this issue report is writing in Chinese.
写字机一般是使用gcode来描述刀头（笔）的运动的方向的。gcode是一连串的向量组成的文件，也就是模拟了人手在写字时的笔尖的移动。

Handright模拟出来的手写笔记非常非常的真实，而将这些模拟的图片使用写字机还原到纸上却有比较大的问题：

- 由于使用PIL输出图片，只能够将图片转换成gcode向量文件，可由于汉字的笔画是有厚度的，导致了直接用现有的转换方式无法转换出最佳的路径。

潜在的解决方案：

1. 将Handright输出图片转换为模拟人手写的gcode向量格式（优化困难）
2. 使用已有的商业软件（炽写、奎享雕刻等）创建单线字字形的gcode向量文件，然后使用Handright将每一个笔顺的向量集合作为整体旋转平移（较为简单）
3. 使用含有笔划及其位置的字库创建单线字字形

P.S.商业软件的单线字解决方案很简单粗暴，直接读取人手写的路径创建专门的字库，但这种做法也破坏了人手写的随机性.
P.S.2Handright对笔画的区分，受限于笔者代码水平，实在没看懂[doge]

示例：
商业软件的单线字生成gcode：
![微信截图_20200808131032](https://user-images.githubusercontent.com/40327863/89702949-a40f7200-d978-11ea-83a2-eb7da65252d0.png)

使用Handright生成png图片之后使用软件自动转换为gcode：
![微信截图_20200808131032](https://user-images.githubusercontent.com/40327863/89703000-53e4df80-d979-11ea-97dc-3f8a0f48f1fc.png)

**Comment by RuofengX** [comment]
此外抛弃商用的单线字手写字库，完全使用开源项目来用gcode模拟汉字笔画的顺序也是一个大问题，笔者找到了一个基于js的模拟笔画的项目，不过还没有深入的研究。
项目地址：https://github.com/chanind/hanzi-writer 演示：https://hanziwriter.org/demo.html

**Comment by Gsllchb** [comment]
归根结底还是”矢量 vs 点阵“的问题，之前不少人反馈过类似的问题：  #7 
这两者是两条截然不同的技术路线，而Handright选择了”点阵“这条路。
我个人相信”矢量“的方案是更完美的方案。如果采用矢量方案的话，我会选择另起炉灶，写一个新的库，而不是重构Handright。
然我已不在年少，不太可能还有时间、精力和激情去实现这个目标了。。。

**Comment by RuofengX** [comment]
有一个折衷的方案就是使用商业软件来生成单线字的gcode，之后使用类似handright的方法来对每一个笔画进行微调。我最近正在写这个。

**Comment by 14790897** [comment]
主要是没钱,有钱一切都好说

**Comment by 14790897** [comment]
https://vectorizer.ai/      找到一个转换成矢量图片的网站
