### ISSUE TITLE
能不能添加一个行角度随机调节的功能

### ISSUE THREAD

**Issue by indiefun** [Gsllchb/Handright#29]
参数调整好后，已经很难分辨单个文字是否是手写还是打印的了
但是当A4纸打印出来整篇的文字后，会发现整体看上去还是不像手写的
因为行的水平角度太直了，一般白纸上手写文字，都会越写越向上偏，很难都是水平的
希望能添加一个行水平角度扰动参数，取值范围可能在 (90°, -90°) 之间，当然不可能这么大角度，一般就正负5°以内估计就差不多了
正数表示行越往右越向上偏，负数表示行越往右越向下偏
只是大概这么个想法，还不太完善，如果作者还会继续完善，那么可以深入讨论一下，谢谢
没有配图，不好意思

**Comment by Gsllchb** [comment]
我并不认为正常情况下会有人“刻意”将一行字整体写歪。
正常情况下，应仅仅是在一个水平横行的基准上上下浮动。（已有功能）

**Comment by Gsllchb** [comment]
test



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月8日(周四) 晚上10:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Your ***@***.***&gt;;
主题: Re: [Gsllchb/Handright] 能不能添加一个行角度随机调节的功能 (#29)




 
我并不认为正常情况下会有人“刻意”将一行字整体写歪。
 正常情况下，应仅仅是在一个水平横行的基准上上下浮动。（已有功能）
