### ISSUE TITLE
中文字符和英文字符宽度不一致问题

### ISSUE THREAD

**Issue by Anthem-whisper** [Gsllchb/Handright#35]
如图，按照中国人的书写习惯，通常一个中文字符和一个英文或者数字字符宽度是不一致的
希望能增加这方面的功能

<img src='https://user-images.githubusercontent.com/57484186/161271073-f950f900-9463-43c8-92e1-fa9029a8476e.png' align='left' style='width:400px;height:700 px'>
<img src='https://user-images.githubusercontent.com/57484186/161271194-2246eeb7-d247-4cf4-aee7-9ea1a5700a15.png' align='right' style='width:400px;height:700 px'>

**Comment by Gsllchb** [comment]
当前英文和中文的字符宽度就是不一样的。你要的应该是中文和英文的"字间距"不一样。建议你把word_spacing调小一点，再看下效果。

**Comment by Anthem-whisper** [comment]
上图我的设置的word_spacing=1.2，我把word_spacing设置为0之后还是只有下图的效果
![image](https://user-images.githubusercontent.com/57484186/161412085-009d06f3-bd4e-4cad-acbe-74b31a89f479.png)

**Comment by Gsllchb** [comment]
建议你换个字体，你用的这个字体左右留白太多了。
