### ISSUE TITLE
有没有做字库检查？

### ISSUE THREAD

**Issue by phlas-end** [Gsllchb/Handright#41]
在处理大量数据的时候，可能会涉及到多个字体ttf，但每个ttf中的字种类并不相同，如果在绘制时出现了不存在的字，请问会返回什么呢？

**Comment by phlas-end** [comment]
即，我传入的字，在字库ttf中不存在时，会返回什么

**Comment by Gsllchb** [comment]
在那个字的地方会留白。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月24日(周一) 中午1:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Gsllchb/Handright] 有没有做字库检查？ (Issue #41)




 
即，我传入的字，在字库ttf中不存在时，会返回什么

**Comment by phlas-end** [comment]
好的，十分感谢

**Comment by 14790897** [comment]
考虑将留白地方换成普通字体吗？
