### ISSUE TITLE
建议引进抗锯齿算法

### ISSUE THREAD

**Issue by ChaseTheDark** [Gsllchb/Handright#43]
生成的文字为单色文字，没有灰度变化，导致锯齿感始终比较强，建议引进抗锯齿算法

我字体大小以及设置为264了，按理来说分辨率还不错了，但还是由锯齿
![image](https://github.com/Gsllchb/Handright/assets/88815701/2197027a-a308-4c26-a206-c0fb2b766408)

**Comment by Gsllchb** [comment]
虽然增加灰色的过渡会让结果在电子屏幕上表现得更好一些，但是如果将图片打印出来却可能使笔迹的边缘变“糊”。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月10日(周三) 中午1:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Gsllchb/Handright] 建议引进抗锯齿算法 (Issue #43)




 
生成的文字为单色文字，没有灰度变化，导致锯齿感始终比较强，建议引进抗锯齿算法
 
我字体大小以及设置为264了，按理来说分辨率还不错了，但还是由锯齿

**Comment by Slipstream-Max** [comment]
这个锯齿可以放大（比如4x4）背景文件缓解 这样他就能以更高像素“写”出这个字了
