### ISSUE TITLE
部分文字显示不出来

### ISSUE THREAD

**Issue by cp319** [Gsllchb/Handright#44]
请简明扼要地陈述您的问题。
![image](https://github.com/Gsllchb/Handright/assets/38431724/a12ba1d7-e1c1-4ac4-a739-befbd1ca02fb)
当我在尝试使用handright生成指定字体的文字时，出现了如图所示的错误效果，想询问问题的原因和可能的解决方法

**Comment by Gsllchb** [comment]
可能是由于你用的字体里没有这个字，换个字体试试。
