### ISSUE TITLE
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by nonusx** [Gsllchb/Handright#48]
1. 您做了什么？
运行了tutorial.md中的实例程序（我替换了字体路径和输出路径）
2. 您希望发生什么？
成功运行
3. 实际上发生了什么？
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
4. python3, pillow9.5

请附上重现该bug的代码、图片（如果有的话）以及其它重现该bug所必须的东西。此外，重现bug的脚本应尽量使用最精简的代码以及最少的依赖项。

**Comment by Gsllchb** [comment]
我使用Python3.9+Pillow9.5.0测试了一下，未发现你说的问题。

另外，我查阅Pillow的文档发现，FreeTypeFont.getsize虽然在9.2.0版本被标记为`deprecated`，但在10.0.0版本才会被移除。
