### ISSUE TITLE
正确的下一行；自动下一行

### ISSUE THREAD

**Issue by KuekHaoYang** [Gsllchb/Handright#57]
在英文文本中存在一个问题，例如“you”这个词的书写。第一行只有字母“y”，占满了整行，而“ou”却被挤到了下一行，导致在某些情况下字母的显示不完整。英文字体的大小似乎超出了可用空间，从而影响了排版效果。

![image](https://github.com/user-attachments/assets/ba3b7de3-f09b-4375-a757-b7d4c17b521b)

**Comment by Gsllchb** [comment]
这个库没有考虑英文的场景，因此不应该用于英文场景。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月4日(周三) 上午10:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Gsllchb/Handright] 正确的下一行；自动下一行 (Issue #57)




 
在英文文本中存在一个问题，例如“you”这个词的书写。第一行只有字母“y”，占满了整行，而“ou”却被挤到了下一行，导致在某些情况下字母的显示不完整。英文字体的大小似乎超出了可用空间，从而影响了排版效果。
 
image.png (view on web)
